from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime, date

db = SQLAlchemy()


class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(80), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
    stories_generated = db.Column(db.Integer, default=0)
    is_admin = db.Column(db.Boolean, default=False)
    is_active_flag = db.Column(db.Boolean, default=True)
    last_login = db.Column(db.DateTime)

    def set_password(self, password):
        """Hash and set the user's password"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Check if the provided password matches the hash"""
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'

    def increment_stories_count(self):
        """Increment the number of stories generated by the user"""
        self.stories_generated += 1
        db.session.commit()

    def update_last_login(self):
        """Update the last login timestamp"""
        self.last_login = datetime.utcnow()
        db.session.commit()

    @property
    def is_active(self):
        """Override is_active for Flask-Login"""
        return self.is_active_flag


class SiteVisit(db.Model):
    """Track all site visits for analytics"""
    __tablename__ = 'site_visits'

    id = db.Column(db.Integer, primary_key=True)
    ip_address = db.Column(db.String(45))
    user_agent = db.Column(db.String(500))
    page = db.Column(db.String(200))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=True)
    visited_at = db.Column(db.DateTime, default=datetime.utcnow)
    referrer = db.Column(db.String(500))

    user = db.relationship('User', backref='visits')

    def __repr__(self):
        return f'<SiteVisit {self.ip_address} - {self.page}>'

    @classmethod
    def get_daily_visits(cls, days=30):
        """Get daily visit counts for the last N days"""
        from sqlalchemy import func, cast, Date
        start_date = datetime.utcnow() - timedelta(days=days)
        return db.session.query(
            cast(cls.visited_at, Date).label('visit_date'),
            func.count(cls.id).label('visit_count')
        ).filter(
            cls.visited_at >= start_date
        ).group_by(
            cast(cls.visited_at, Date)
        ).order_by(
            cast(cls.visited_at, Date)
        ).all()

    @classmethod
    def get_stats(cls, days=30):
        """Get visit statistics"""
        from datetime import timedelta
        start_date = datetime.utcnow() - timedelta(days=days)
        
        total_visits = cls.query.filter(cls.visited_at >= start_date).count()
        unique_visitors = db.session.query(
            func.count(func.distinct(cls.ip_address))
        ).filter(cls.visited_at >= start_date).scalar()
        
        # Top visited pages
        top_pages = db.session.query(
            cls.page, func.count(cls.id).label('count')
        ).filter(
            cls.visited_at >= start_date
        ).group_by(cls.page).order_by(
            db.desc('count')
        ).limit(10).all()
        
        return {
            'total_visits': total_visits,
            'unique_visitors': unique_visitors,
            'top_pages': top_pages
        }


from datetime import timedelta
